apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: parultestapp 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: parultestapp 
  template:
    metadata: 
      labels:
        app: parultestapp
    spec:
      containers:
      - name: parultestapp
        image: parul_technocrat/sprint6dockerjenkinsgcloud:tagversion 
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata:
  name: parultestapp-svc 
  labels:
    app: parultestapp 
spec:
  type: LoadBalancer 
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 8080 
  selector:
    app: parultestapp
